name: go-kv-build
on: [push]
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.7' 
      - run: go build -v -ldflags="-s -w" . && ./go-kv-bench
